server:
  port: 9004
  servlet:
    context-path: /storage
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://47.103.133.107:8761/eureka/
nacos:
  discovery:
    server-addr: 47.103.133.107:8848
  config:
    server-addr: 47.103.133.107:8848

spring:
  application:
    name: storage
  datasource:
    url: jdbc:mysql://taifangjin.rwlb.rds.aliyuncs.com:3306/seata_storage?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: dev
    password: Lgy12500
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 47.103.133.107:8848
    sentinel:
      transport:
        dashboard: 47.103.133.107:8080
      #eager: true
#seata:
#  enabled: true
#  application-id: storage-seata
#  tx-service-group: my_test_tx_group
#  enable-auto-data-source-proxy: true
#  service:
#    vgroup-mapping:
#      my_test_tx_group: my_test_tx_group
#    grouplist:
#      - localhost:8091
#  config:
#    type: nacos
#    nacos:
#      namespace:
#      serverAddr: 47.103.133.107:8848
#      group: SEATA_GROUP
#  registry:
#    type: nacos
#    nacos:
#      namespace:
#      server-addr: 47.103.133.107:8848

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-underline: true
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  type-aliases-package: com.example.storageservice.entity