server:
  port: 9004
  servlet:
    context-path: /storage
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka/
nacos:
  discovery:
    server-addr: 47.103.133.107:8848
  config:
    server-addr: 47.103.133.107:8848

spring:
  application:
    name: storage
  datasource:
    url: jdbc:mysql://rm-bp1v9eku86360zau23o.mysql.rds.aliyuncs.com:3306/seata_order?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Lgy12500
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 47.103.133.107:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      #eager: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-underline: true
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  type-aliases-package: com.example.storageservice.entity